/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'propertyType' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'area' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ImagePaths = IDL.Record({
  'heroImage' : IDL.Text,
  'beforeAfterGallery' : IDL.Vec(IDL.Text),
  'serviceCard1' : IDL.Text,
  'serviceCard2' : IDL.Text,
  'serviceCard3' : IDL.Text,
  'serviceCard4' : IDL.Text,
});
export const ServiceRate = IDL.Record({
  'pvc' : IDL.Nat,
  'wallMolding' : IDL.Nat,
  'popGypsum' : IDL.Nat,
});
export const TimeSlotAvailability = IDL.Record({
  'slot1pm' : IDL.Bool,
  'slot4pm' : IDL.Bool,
  'slot7pm' : IDL.Bool,
  'slot10am' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateEstimate' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [Booking],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImagePaths' : IDL.Func([], [ImagePaths], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
  'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateImagePaths' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateTimeSlotAvailability' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'propertyType' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'area' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ImagePaths = IDL.Record({
    'heroImage' : IDL.Text,
    'beforeAfterGallery' : IDL.Vec(IDL.Text),
    'serviceCard1' : IDL.Text,
    'serviceCard2' : IDL.Text,
    'serviceCard3' : IDL.Text,
    'serviceCard4' : IDL.Text,
  });
  const ServiceRate = IDL.Record({
    'pvc' : IDL.Nat,
    'wallMolding' : IDL.Nat,
    'popGypsum' : IDL.Nat,
  });
  const TimeSlotAvailability = IDL.Record({
    'slot1pm' : IDL.Bool,
    'slot4pm' : IDL.Bool,
    'slot7pm' : IDL.Bool,
    'slot10am' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateEstimate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [Booking],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImagePaths' : IDL.Func([], [ImagePaths], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
    'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminUser' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateImagePaths' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTimeSlotAvailability' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };