/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'propertyType' : IDL.Text,
  'area' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const ServiceRate = IDL.Record({
  'pvc' : IDL.Nat,
  'wallMolding' : IDL.Nat,
  'popGypsum' : IDL.Nat,
});
export const TimeSlotAvailability = IDL.Record({
  'slot1pm' : IDL.Bool,
  'slot4pm' : IDL.Bool,
  'slot7pm' : IDL.Bool,
  'slot10am' : IDL.Bool,
});

export const idlService = IDL.Service({
  'calculateEstimate' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [Booking],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
  'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
  'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateTimeSlotAvailability' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'propertyType' : IDL.Text,
    'area' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const ServiceRate = IDL.Record({
    'pvc' : IDL.Nat,
    'wallMolding' : IDL.Nat,
    'popGypsum' : IDL.Nat,
  });
  const TimeSlotAvailability = IDL.Record({
    'slot1pm' : IDL.Bool,
    'slot4pm' : IDL.Bool,
    'slot7pm' : IDL.Bool,
    'slot10am' : IDL.Bool,
  });
  
  return IDL.Service({
    'calculateEstimate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [Booking],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
    'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
    'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTimeSlotAvailability' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };