/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'propertyType' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'area' : IDL.Opt(IDL.Nat),
  'date' : IDL.Text,
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'location' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StoredImage = IDL.Record({
  'path' : IDL.Text,
  'image' : ExternalBlob,
});
export const ImagePaths = IDL.Record({
  'heroImage' : IDL.Text,
  'beforeAfterGallery' : IDL.Vec(StoredImage),
  'serviceCard1' : IDL.Opt(StoredImage),
  'serviceCard2' : IDL.Opt(StoredImage),
  'serviceCard3' : IDL.Opt(StoredImage),
  'serviceCard4' : IDL.Opt(StoredImage),
});
export const ServiceRate = IDL.Record({
  'pvc' : IDL.Nat,
  'wallMolding' : IDL.Nat,
  'popGypsum' : IDL.Nat,
});
export const TimeSlotAvailability = IDL.Record({
  'slot1pm' : IDL.Bool,
  'slot4pm' : IDL.Bool,
  'slot7pm' : IDL.Bool,
  'slot10am' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateEstimate' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [Booking],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImagePaths' : IDL.Func([], [ImagePaths], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
  'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateImagePaths' : IDL.Func(
      [
        IDL.Record({
          'heroImage' : IDL.Text,
          'beforeAfterGallery' : IDL.Vec(StoredImage),
          'serviceCard1' : IDL.Opt(StoredImage),
          'serviceCard2' : IDL.Opt(StoredImage),
          'serviceCard3' : IDL.Opt(StoredImage),
          'serviceCard4' : IDL.Opt(StoredImage),
        }),
      ],
      [],
      [],
    ),
  'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateTimeSlotAvailability' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'uploadImage' : IDL.Func([ExternalBlob, IDL.Text], [StoredImage], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'propertyType' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'area' : IDL.Opt(IDL.Nat),
    'date' : IDL.Text,
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'location' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StoredImage = IDL.Record({ 'path' : IDL.Text, 'image' : ExternalBlob });
  const ImagePaths = IDL.Record({
    'heroImage' : IDL.Text,
    'beforeAfterGallery' : IDL.Vec(StoredImage),
    'serviceCard1' : IDL.Opt(StoredImage),
    'serviceCard2' : IDL.Opt(StoredImage),
    'serviceCard3' : IDL.Opt(StoredImage),
    'serviceCard4' : IDL.Opt(StoredImage),
  });
  const ServiceRate = IDL.Record({
    'pvc' : IDL.Nat,
    'wallMolding' : IDL.Nat,
    'popGypsum' : IDL.Nat,
  });
  const TimeSlotAvailability = IDL.Record({
    'slot1pm' : IDL.Bool,
    'slot4pm' : IDL.Bool,
    'slot7pm' : IDL.Bool,
    'slot10am' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateEstimate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [Booking],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImagePaths' : IDL.Func([], [ImagePaths], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getServiceRates' : IDL.Func([], [ServiceRate], ['query']),
    'getTimeSlotAvailability' : IDL.Func([], [TimeSlotAvailability], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateImagePaths' : IDL.Func(
        [
          IDL.Record({
            'heroImage' : IDL.Text,
            'beforeAfterGallery' : IDL.Vec(StoredImage),
            'serviceCard1' : IDL.Opt(StoredImage),
            'serviceCard2' : IDL.Opt(StoredImage),
            'serviceCard3' : IDL.Opt(StoredImage),
            'serviceCard4' : IDL.Opt(StoredImage),
          }),
        ],
        [],
        [],
      ),
    'updateServiceRates' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTimeSlotAvailability' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'uploadImage' : IDL.Func([ExternalBlob, IDL.Text], [StoredImage], []),
  });
};

export const init = ({ IDL }) => { return []; };