/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'service' : string,
  'propertyType' : string,
  'owner' : [] | [Principal],
  'area' : [] | [bigint],
  'date' : string,
  'createdAt' : Time,
  'fullName' : string,
  'mobileNumber' : string,
  'location' : string,
  'timeSlot' : string,
}
export type ExternalBlob = Uint8Array;
export interface ImagePaths {
  'heroImage' : string,
  'beforeAfterGallery' : Array<StoredImage>,
  'serviceCard1' : [] | [StoredImage],
  'serviceCard2' : [] | [StoredImage],
  'serviceCard3' : [] | [StoredImage],
  'serviceCard4' : [] | [StoredImage],
}
export interface ServiceRate {
  'pvc' : bigint,
  'wallMolding' : bigint,
  'popGypsum' : bigint,
}
export interface StoredImage { 'path' : string, 'image' : ExternalBlob }
export type Time = bigint;
export interface TimeSlotAvailability {
  'slot1pm' : boolean,
  'slot4pm' : boolean,
  'slot7pm' : boolean,
  'slot10am' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateEstimate' : ActorMethod<[string, bigint], [] | [bigint]>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string, [] | [bigint]],
    Booking
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImagePaths' : ActorMethod<[], ImagePaths>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getServiceRates' : ActorMethod<[], ServiceRate>,
  'getTimeSlotAvailability' : ActorMethod<[], TimeSlotAvailability>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateImagePaths' : ActorMethod<
    [
      {
        'heroImage' : string,
        'beforeAfterGallery' : Array<StoredImage>,
        'serviceCard1' : [] | [StoredImage],
        'serviceCard2' : [] | [StoredImage],
        'serviceCard3' : [] | [StoredImage],
        'serviceCard4' : [] | [StoredImage],
      },
    ],
    undefined
  >,
  'updateServiceRates' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'updateTimeSlotAvailability' : ActorMethod<
    [boolean, boolean, boolean, boolean],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob, string], StoredImage>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];